server:
  port: 8888

spring:
  application:
    name: Trello-be
  datasource:
    url: jdbc:mysql://localhost:3310/trello
    username: root
    password: 3124
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: messages
    fallback-to-system-locale: false
    default-locale: vi

jwt:
  signerKey: "WJOeduukzBrxaCcS39uEWucilc17mGjl+Dace+pVfX9JG1nJkPoVbOAOD4FEGvHE"

